server:
  context-path: /expert
  port: 8098


#dubbo config
dubbo:
  zookeeper:
    address: 10.101.86.121:2181
  version:
  uc:
    version:

# shiro cas
shiro:
  serverUrlPrefix: http://10.101.86.109:${server.port}${server.context-path}

cas:
  serverUrlPrefix: http://10.101.86.109:8093/sso


# messageSource
spring:
  messages:
    basename: msg/messages-pro,msg/messages

  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 3000
    host: 10.101.86.122
    password: R52P6vYGrCQXSaZf
    port: 6379

  #spring boot admin config
  boot:
    admin:
      url: http://10.101.86.121:8092
      client:
        name: identify-view
        prefer-ip: true

activiti:
  rest:
    prefix: http://10.101.86.113:8094