server:
  context-path: /expert
  port: 8082


#dubbo config
dubbo:
  zookeeper:
    address: 172.16.5.216:2181
  version:
  uc:
    version:

# shiro cas
shiro:
  serverUrlPrefix: http://172.16.5.217:${server.port}${server.context-path}

cas:
  serverUrlPrefix: http://172.16.5.217/sso


# messageSource
spring:
  messages:
    basename: msg/messages-test,msg/messages

  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 3000
    host: 172.16.5.220
    password: zhfaredispasswd
    port: 6379

  #spring boot admin config
  boot:
    admin:
      url: http://172.16.5.210:12306
      client:
        name: identify-view
        prefer-ip: true

activiti:
  rest:
    prefix: http://172.16.5.213:8080