server:
  tomcat:
    basedir: /usr/local/project/springboot-tomcat/tmp
  context-path: /identify
  port: 7010
  session:
    cookie:
      path: /


#dubbo config
dubbo:
  zookeeper:
    address: 172.16.5.210:2181
  version:
  uc:
    version:

# shiro cas
shiro:
  serverUrlPrefix: http://222.190.107.66:${server.port}${server.context-path}

cas:
  serverUrlPrefix: http://222.190.107.66/sso


# messageSource
spring:
  messages:
    basename: msg/messages-dev,msg/messages

  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 3000
    host: 172.16.5.208
    password:
    port: 6379

  #spring boot admin config
  boot:
    admin:
      url: http://172.16.5.210:12306
      client:
        name: identify-view
        prefer-ip: true

activiti:
  rest:
    prefix: http://172.16.5.213:8080
