server:
  context-path: /api
  port: 8083


#dubbo config
dubbo:
  zookeeper:
    address: 172.16.5.210:2181
  version:
  uc:
    version:


# messageSource
spring:
  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 3000
    host: 172.16.5.208
    password:
    port: 6379

  #spring boot admin config
  boot:
    admin:
      url: http://172.16.5.210:12306
      client:
        name: identify-rest
        prefer-ip: true