server:
  context-path: /services
  port: 8082


#dubbo config
dubbo:
  zookeeper:
    address: 172.16.5.216:2181
  version:
  uc:
    version:
  supervise:
    version:
# jdbc
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.5.13:1521:testdb
    username: zhfa
    password: zhfapasswd2018
  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 5000
    host: 172.16.5.220
    password: zhfaredispasswd
    port: 6379


  #spring boot admin
  boot:
    admin:
      url: http://172.16.5.210:12306
      client:
        name: identify-service
        prefer-ip: true

activiti:
  rest:
    prefix: http://172.16.5.213:8080