server:
  context-path: /services
  port: 8097


#dubbo config
dubbo:
  zookeeper:
    address: 10.101.86.121:2181
  version:
  uc:
    version:
  supervise:
    version:
# jdbc
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.196.68.204:1621/njdx_njracdb2
    username: fangan_zhfa
    password: H6tfVIZ2
  #redis 配置
  redis:
    pool:
      min-idle: 50
      max-idle: 200
      max-active: 20
      max-wait: 5000
    host: 10.101.86.122
    password: R52P6vYGrCQXSaZf
    port: 6379


  #spring boot admin
  boot:
    admin:
      url: http://10.101.86.121:8092
      client:
        name: identify-service
        prefer-ip: true

activiti:
  rest:
    prefix: http://10.101.86.113:8094